<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>Source file</title>
<style type="text/css">
/* highlight theme: Emacs Editor */
body.hl	{ background-color:#ffffff; }
pre.hl	{ color:#000000; background-color:#ffffff; font-size:10pt; font-family:'Courier New',monospace;}
.hl.num { color:#000000; }
.hl.esc { color:#ff00ff; }
.hl.str { color:#bd8d8b; }
.hl.pps { color:#bd8d8b; }
.hl.slc { color:#ac2020; font-style:italic; }
.hl.com { color:#ac2020; font-style:italic; }
.hl.ppc { color:#000000; }
.hl.opt { color:#000000; }
.hl.ipl { color:#ff00ff; }
.hl.lin { color:#555555; }
.hl.kwa { color:#9c20ee; font-weight:bold; }
.hl.kwb { color:#208920; }
.hl.kwc { color:#0000ff; }
.hl.kwd { color:#000000; }
</style>
</head>
<body class="hl">
<pre class="hl"><span class="hl slc">#!/bin/sh</span>

<span class="hl kwb">echo</span> <span class="hl str">&apos;needs to be set up&apos;</span>
</pre>
</body>
</html>
<!--HTML generated by highlight 3.41, http://www.andre-simon.de/-->
